# Generated by Django 3.1.4 on 2020-12-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
