# Generated by Django 3.1.4 on 2020-12-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike'), ('Dislike', 'Dislike')], max_length=8),
        ),
    ]
